-- Migracion 015: catalogo de equipos tecnologicos (categorias + productos).
-- Catalogo de referencia global (no depende de empresa_id) -- 74
-- categorias, 347 productos.

create table if not exists categorias (
    id      serial primary key,
    nombre  varchar(100) not null unique
);

create table if not exists productos (
    id            serial primary key,
    categoria_id  integer not null references categorias(id) on update cascade on delete restrict,
    nombre        varchar(150) not null,
    constraint uq_productos_categoria_nombre unique (categoria_id, nombre)
);

create index if not exists idx_productos_categoria_id on productos(categoria_id);

-- Categorias
insert into categorias (nombre) values
    ('Router'),
    ('Router 4G/5G'),
    ('Router Wi-Fi'),
    ('Sistema Wi-Fi mesh'),
    ('ONT / Módem'),
    ('Switch'),
    ('Punto de acceso'),
    ('Controlador WLAN'),
    ('Gateway de seguridad / SD-WAN'),
    ('Firewall'),
    ('Balanceador de carga'),
    ('Radioenlace'),
    ('Transceptor SFP'),
    ('Servidor rack'),
    ('Servidor torre'),
    ('Servidor blade'),
    ('Hiperconvergente'),
    ('NAS'),
    ('Almacenamiento SAN'),
    ('Librería de cintas'),
    ('UPS'),
    ('Regulador de voltaje'),
    ('PDU'),
    ('Switch KVM'),
    ('Rack / gabinete'),
    ('Laptop'),
    ('Computadora de escritorio'),
    ('Estación de trabajo'),
    ('Mini PC'),
    ('Cliente ligero'),
    ('Computadora de placa única'),
    ('Procesador'),
    ('Tarjeta gráfica'),
    ('Memoria RAM'),
    ('Disco SSD'),
    ('Disco duro HDD'),
    ('Disco externo'),
    ('Monitor'),
    ('Proyector'),
    ('Pantalla interactiva'),
    ('Impresora láser'),
    ('Multifuncional'),
    ('Impresora térmica / etiquetas'),
    ('Plotter'),
    ('Impresora 3D'),
    ('Escáner'),
    ('Lector de código de barras'),
    ('Terminal móvil robusta'),
    ('Terminal punto de venta'),
    ('Lector biométrico'),
    ('Lector de tarjetas inteligentes'),
    ('Llave de seguridad FIDO2'),
    ('Token OTP'),
    ('HSM'),
    ('Appliance PAM'),
    ('Cámara web'),
    ('Teclado / ratón'),
    ('Audífonos / diadema'),
    ('Estación de acoplamiento'),
    ('Teléfono IP'),
    ('Central telefónica IP'),
    ('Videoconferencia'),
    ('Radio portátil'),
    ('Smartphone'),
    ('Tableta'),
    ('Reloj inteligente'),
    ('Cámara IP'),
    ('NVR'),
    ('Control de acceso'),
    ('Domótica / IoT'),
    ('PLC'),
    ('HMI'),
    ('Dron'),
    ('Visor VR / AR')
on conflict (nombre) do nothing;

-- Productos (se enlazan a su categoria por nombre, sin depender de los id)
insert into productos (categoria_id, nombre)
select c.id, v.producto
from (values
    ('Router', 'TP-Link ER605'),
    ('Router', 'TP-Link ER7206'),
    ('Router', 'Cisco ISR 1111-4P'),
    ('Router', 'Cisco ISR 4331'),
    ('Router', 'MikroTik RB5009UG+S+IN'),
    ('Router', 'MikroTik hEX RB750Gr3'),
    ('Router', 'Ubiquiti EdgeRouter X'),
    ('Router', 'Juniper SRX300'),
    ('Router 4G/5G', 'Huawei B535-232'),
    ('Router 4G/5G', 'Teltonika RUT241'),
    ('Router 4G/5G', 'Teltonika RUTX50'),
    ('Router Wi-Fi', 'TP-Link Archer AX55'),
    ('Router Wi-Fi', 'ASUS RT-AX86U'),
    ('Router Wi-Fi', 'Netgear Nighthawk RAX50'),
    ('Sistema Wi-Fi mesh', 'TP-Link Deco X20'),
    ('Sistema Wi-Fi mesh', 'eero 6+'),
    ('Sistema Wi-Fi mesh', 'Google Nest Wifi Pro'),
    ('Sistema Wi-Fi mesh', 'ASUS ZenWiFi XT8'),
    ('ONT / Módem', 'Huawei HG8145V5'),
    ('ONT / Módem', 'ZTE F670L'),
    ('Switch', 'Cisco Catalyst 9200L-24P-4G'),
    ('Switch', 'Cisco Catalyst 9300-48P'),
    ('Switch', 'Cisco CBS350-24P-4G'),
    ('Switch', 'Aruba 2930F 24G'),
    ('Switch', 'HPE Aruba Instant On 1930 24G'),
    ('Switch', 'Ubiquiti UniFi USW-Pro-24-PoE'),
    ('Switch', 'TP-Link TL-SG3428'),
    ('Switch', 'Juniper EX2300-24P'),
    ('Switch', 'MikroTik CRS326-24G-2S+RM'),
    ('Switch', 'Dell PowerSwitch S5248F-ON'),
    ('Punto de acceso', 'Ubiquiti UniFi U6 Pro'),
    ('Punto de acceso', 'Ubiquiti UniFi U6 Lite'),
    ('Punto de acceso', 'Cisco Meraki MR36'),
    ('Punto de acceso', 'Cisco Catalyst 9120AXI'),
    ('Punto de acceso', 'Aruba AP-515'),
    ('Punto de acceso', 'HPE Aruba Instant On AP22'),
    ('Punto de acceso', 'TP-Link Omada EAP650'),
    ('Punto de acceso', 'Ruckus R650'),
    ('Controlador WLAN', 'Cisco Catalyst 9800-L'),
    ('Controlador WLAN', 'Aruba 7205'),
    ('Controlador WLAN', 'TP-Link Omada OC200'),
    ('Controlador WLAN', 'Ubiquiti UniFi Cloud Key Gen2 Plus'),
    ('Gateway de seguridad / SD-WAN', 'Cisco Meraki MX68'),
    ('Gateway de seguridad / SD-WAN', 'Cisco Meraki MX85'),
    ('Gateway de seguridad / SD-WAN', 'Ubiquiti UniFi Dream Machine Pro'),
    ('Firewall', 'Fortinet FortiGate 60F'),
    ('Firewall', 'Fortinet FortiGate 100F'),
    ('Firewall', 'Palo Alto Networks PA-440'),
    ('Firewall', 'Palo Alto Networks PA-3220'),
    ('Firewall', 'Cisco Firepower 1010'),
    ('Firewall', 'Sophos XGS 2100'),
    ('Firewall', 'SonicWall TZ370'),
    ('Firewall', 'Check Point Quantum Spark 1570'),
    ('Balanceador de carga', 'F5 BIG-IP i2800'),
    ('Balanceador de carga', 'F5 BIG-IP i4800'),
    ('Radioenlace', 'Ubiquiti NanoBeam 5AC Gen2'),
    ('Radioenlace', 'Ubiquiti LiteBeam 5AC Gen2'),
    ('Radioenlace', 'MikroTik SXTsq 5 ac'),
    ('Radioenlace', 'Cambium ePMP Force 300-25'),
    ('Transceptor SFP', 'Cisco GLC-SX-MMD'),
    ('Transceptor SFP', 'Cisco SFP-10G-SR'),
    ('Servidor rack', 'Dell PowerEdge R650'),
    ('Servidor rack', 'Dell PowerEdge R750'),
    ('Servidor rack', 'Dell PowerEdge R760'),
    ('Servidor rack', 'HPE ProLiant DL360 Gen10 Plus'),
    ('Servidor rack', 'HPE ProLiant DL380 Gen11'),
    ('Servidor rack', 'Lenovo ThinkSystem SR630 V2'),
    ('Servidor rack', 'Lenovo ThinkSystem SR650 V3'),
    ('Servidor rack', 'Cisco UCS C220 M6'),
    ('Servidor torre', 'Dell PowerEdge T150'),
    ('Servidor torre', 'Dell PowerEdge T350'),
    ('Servidor torre', 'Dell PowerEdge T550'),
    ('Servidor torre', 'HPE ProLiant ML30 Gen10 Plus'),
    ('Servidor torre', 'HPE ProLiant ML110 Gen10'),
    ('Servidor torre', 'Lenovo ThinkSystem ST50 V2'),
    ('Servidor torre', 'Lenovo ThinkSystem ST250 V2'),
    ('Servidor blade', 'HPE Synergy 480 Gen10'),
    ('Servidor blade', 'Cisco UCS B200 M5'),
    ('Servidor blade', 'Dell PowerEdge MX750c'),
    ('Hiperconvergente', 'Dell VxRail E660'),
    ('Hiperconvergente', 'Dell VxRail P670F'),
    ('Hiperconvergente', 'HPE SimpliVity 380 Gen10'),
    ('NAS', 'Synology DS224+'),
    ('NAS', 'Synology DS923+'),
    ('NAS', 'Synology RS1221+'),
    ('NAS', 'QNAP TS-464'),
    ('NAS', 'QNAP TS-873A'),
    ('NAS', 'WD My Cloud EX2 Ultra'),
    ('Almacenamiento SAN', 'Dell PowerStore 500T'),
    ('Almacenamiento SAN', 'Dell PowerVault ME5024'),
    ('Almacenamiento SAN', 'NetApp AFF A250'),
    ('Almacenamiento SAN', 'NetApp FAS2750'),
    ('Almacenamiento SAN', 'HPE MSA 2060'),
    ('Almacenamiento SAN', 'Pure Storage FlashArray//X'),
    ('Almacenamiento SAN', 'IBM FlashSystem 5200'),
    ('Librería de cintas', 'IBM TS4300'),
    ('Librería de cintas', 'Quantum Scalar i3'),
    ('Librería de cintas', 'HPE StoreEver MSL3040'),
    ('Librería de cintas', 'Dell PowerVault TL1000'),
    ('UPS', 'APC Smart-UPS SMT1500'),
    ('UPS', 'APC Smart-UPS SMT3000RM2U'),
    ('UPS', 'APC Back-UPS BX1500M'),
    ('UPS', 'Eaton 5PX 1500'),
    ('UPS', 'Eaton 9PX 3000'),
    ('UPS', 'Vertiv Liebert GXT5 3000'),
    ('UPS', 'CyberPower CP1500PFCLCD'),
    ('Regulador de voltaje', 'APC Line-R LE1200'),
    ('PDU', 'APC AP7900B'),
    ('PDU', 'APC AP7921B'),
    ('PDU', 'Tripp Lite PDUMH20'),
    ('Switch KVM', 'ATEN CS1708A'),
    ('Switch KVM', 'ATEN CL5708'),
    ('Switch KVM', 'Raritan Dominion KX IV-101'),
    ('Rack / gabinete', 'APC NetShelter SX AR3100'),
    ('Rack / gabinete', 'Tripp Lite SR42UB'),
    ('Laptop', 'Dell Latitude 5440'),
    ('Laptop', 'Dell Latitude 7440'),
    ('Laptop', 'Lenovo ThinkPad T14 Gen 4'),
    ('Laptop', 'Lenovo ThinkPad X1 Carbon Gen 11'),
    ('Laptop', 'Lenovo ThinkPad E14 Gen 5'),
    ('Laptop', 'HP EliteBook 840 G10'),
    ('Laptop', 'HP ProBook 450 G10'),
    ('Laptop', 'Apple MacBook Air 13 M3'),
    ('Laptop', 'Apple MacBook Pro 14 M3'),
    ('Laptop', 'ASUS Zenbook 14 OLED'),
    ('Laptop', 'Acer Aspire 5'),
    ('Laptop', 'Microsoft Surface Laptop 5'),
    ('Computadora de escritorio', 'Dell OptiPlex 7010'),
    ('Computadora de escritorio', 'Dell OptiPlex 3000'),
    ('Computadora de escritorio', 'HP ProDesk 400 G9'),
    ('Computadora de escritorio', 'HP EliteDesk 800 G9'),
    ('Computadora de escritorio', 'Lenovo ThinkCentre M70q Gen 4'),
    ('Computadora de escritorio', 'Lenovo ThinkCentre M90t'),
    ('Computadora de escritorio', 'Apple Mac mini M2'),
    ('Computadora de escritorio', 'Apple iMac 24 M3'),
    ('Estación de trabajo', 'Dell Precision 3660'),
    ('Estación de trabajo', 'Dell Precision 5680'),
    ('Estación de trabajo', 'HP Z2 G9'),
    ('Estación de trabajo', 'HP Z4 G5'),
    ('Estación de trabajo', 'Lenovo ThinkStation P3 Tower'),
    ('Estación de trabajo', 'Lenovo ThinkStation P620'),
    ('Mini PC', 'Intel NUC 13 Pro'),
    ('Mini PC', 'ASUS NUC 14 Pro'),
    ('Cliente ligero', 'HP t640'),
    ('Cliente ligero', 'Dell Wyse 5070'),
    ('Cliente ligero', 'IGEL UD3'),
    ('Computadora de placa única', 'Raspberry Pi 5'),
    ('Computadora de placa única', 'Raspberry Pi 4 Model B'),
    ('Computadora de placa única', 'NVIDIA Jetson Orin Nano'),
    ('Computadora de placa única', 'Arduino Uno R4'),
    ('Procesador', 'Intel Core i5-13400'),
    ('Procesador', 'Intel Core i7-14700K'),
    ('Procesador', 'Intel Xeon Silver 4314'),
    ('Procesador', 'AMD Ryzen 5 7600'),
    ('Procesador', 'AMD Ryzen 7 7800X3D'),
    ('Procesador', 'AMD EPYC 9354'),
    ('Tarjeta gráfica', 'NVIDIA GeForce RTX 4060'),
    ('Tarjeta gráfica', 'NVIDIA GeForce RTX 4090'),
    ('Tarjeta gráfica', 'NVIDIA RTX A4000'),
    ('Tarjeta gráfica', 'NVIDIA H100'),
    ('Tarjeta gráfica', 'AMD Radeon RX 7800 XT'),
    ('Memoria RAM', 'Kingston Fury Beast DDR5 16GB'),
    ('Memoria RAM', 'Crucial DDR4 16GB 3200'),
    ('Memoria RAM', 'Corsair Vengeance DDR5 32GB'),
    ('Disco SSD', 'Samsung 870 EVO 1TB'),
    ('Disco SSD', 'Samsung 990 PRO 2TB'),
    ('Disco SSD', 'Crucial MX500 1TB'),
    ('Disco SSD', 'Kingston NV2 1TB'),
    ('Disco SSD', 'WD Blue SN580 1TB'),
    ('Disco duro HDD', 'Seagate BarraCuda 2TB'),
    ('Disco duro HDD', 'Seagate IronWolf 8TB'),
    ('Disco duro HDD', 'Seagate Exos X18 16TB'),
    ('Disco duro HDD', 'WD Red Plus 4TB'),
    ('Disco duro HDD', 'WD Purple 4TB'),
    ('Disco duro HDD', 'Toshiba N300 8TB'),
    ('Disco externo', 'Samsung T7 1TB'),
    ('Disco externo', 'SanDisk Extreme Portable SSD 1TB'),
    ('Disco externo', 'WD My Passport 2TB'),
    ('Disco externo', 'Seagate Expansion 4TB'),
    ('Monitor', 'Dell P2423D'),
    ('Monitor', 'Dell U2723QE'),
    ('Monitor', 'HP E24 G5'),
    ('Monitor', 'LG 27UP850-W'),
    ('Monitor', 'Samsung Odyssey G7'),
    ('Monitor', 'BenQ PD2705U'),
    ('Monitor', 'Lenovo ThinkVision T24i-30'),
    ('Proyector', 'Epson PowerLite 2250U'),
    ('Proyector', 'Epson EB-X49'),
    ('Proyector', 'BenQ MW560'),
    ('Proyector', 'Optoma HD146X'),
    ('Pantalla interactiva', 'Samsung Flip Pro WM75B'),
    ('Pantalla interactiva', 'Microsoft Surface Hub 2S'),
    ('Pantalla interactiva', 'Promethean ActivPanel 9'),
    ('Impresora láser', 'HP LaserJet Pro M404dn'),
    ('Impresora láser', 'HP LaserJet Pro 4001dn'),
    ('Impresora láser', 'Brother HL-L2350DW'),
    ('Impresora láser', 'Brother HL-L5200DW'),
    ('Impresora láser', 'Canon imageCLASS LBP6230dw'),
    ('Impresora láser', 'Lexmark MS521dn'),
    ('Multifuncional', 'HP LaserJet Pro MFP M428fdw'),
    ('Multifuncional', 'Brother MFC-L8900CDW'),
    ('Multifuncional', 'Epson EcoTank L3250'),
    ('Multifuncional', 'Epson EcoTank L5290'),
    ('Multifuncional', 'Canon PIXMA G3110'),
    ('Multifuncional', 'Ricoh IM C3000'),
    ('Multifuncional', 'Xerox VersaLink C405'),
    ('Impresora térmica / etiquetas', 'Zebra ZD421'),
    ('Impresora térmica / etiquetas', 'Zebra ZT411'),
    ('Impresora térmica / etiquetas', 'Zebra GK420d'),
    ('Impresora térmica / etiquetas', 'Epson TM-T20III'),
    ('Impresora térmica / etiquetas', 'Epson TM-T88VI'),
    ('Impresora térmica / etiquetas', 'Brother QL-800'),
    ('Plotter', 'HP DesignJet T230'),
    ('Plotter', 'HP DesignJet T650'),
    ('Plotter', 'Canon imagePROGRAF TM-300'),
    ('Plotter', 'Epson SureColor T3170'),
    ('Impresora 3D', 'Prusa MK4'),
    ('Impresora 3D', 'Bambu Lab X1 Carbon'),
    ('Impresora 3D', 'Bambu Lab P1S'),
    ('Impresora 3D', 'Creality Ender-3 V3'),
    ('Impresora 3D', 'Formlabs Form 4'),
    ('Impresora 3D', 'UltiMaker S5'),
    ('Escáner', 'Fujitsu fi-8170'),
    ('Escáner', 'Fujitsu ScanSnap iX1600'),
    ('Escáner', 'Epson WorkForce DS-530 II'),
    ('Escáner', 'Canon imageFORMULA DR-C225 II'),
    ('Escáner', 'Brother ADS-2200'),
    ('Lector de código de barras', 'Zebra DS2208'),
    ('Lector de código de barras', 'Zebra LI4278'),
    ('Lector de código de barras', 'Honeywell Voyager 1250g'),
    ('Lector de código de barras', 'Honeywell Xenon 1950g'),
    ('Lector de código de barras', 'Datalogic QuickScan QD2430'),
    ('Terminal móvil robusta', 'Zebra TC52'),
    ('Terminal móvil robusta', 'Zebra TC58'),
    ('Terminal móvil robusta', 'Zebra MC3300'),
    ('Terminal móvil robusta', 'Honeywell CT40'),
    ('Terminal móvil robusta', 'Honeywell CT60'),
    ('Terminal punto de venta', 'Verifone V200c'),
    ('Terminal punto de venta', 'PAX A920'),
    ('Lector biométrico', 'ZKTeco K40'),
    ('Lector biométrico', 'ZKTeco SpeedFace-V5L'),
    ('Lector biométrico', 'Suprema BioStation 3'),
    ('Lector biométrico', 'Suprema BioEntry W3'),
    ('Lector biométrico', 'HID DigitalPersona 4500'),
    ('Lector de tarjetas inteligentes', 'HID OMNIKEY 3121'),
    ('Lector de tarjetas inteligentes', 'HID OMNIKEY 5422'),
    ('Lector de tarjetas inteligentes', 'Identiv uTrust SCR3310'),
    ('Llave de seguridad FIDO2', 'Yubico YubiKey 5 NFC'),
    ('Llave de seguridad FIDO2', 'Yubico YubiKey 5C NFC'),
    ('Llave de seguridad FIDO2', 'Yubico YubiKey Bio'),
    ('Llave de seguridad FIDO2', 'Google Titan Security Key'),
    ('Llave de seguridad FIDO2', 'Feitian ePass FIDO'),
    ('Token OTP', 'RSA SecurID SID700'),
    ('Token OTP', 'Thales SafeNet OTP 110'),
    ('Token OTP', 'Feitian c200'),
    ('HSM', 'Thales Luna Network HSM 7'),
    ('HSM', 'Entrust nShield Connect XC'),
    ('HSM', 'Utimaco SecurityServer Se Gen2'),
    ('HSM', 'Yubico YubiHSM 2'),
    ('Appliance PAM', 'BeyondTrust U-Series Appliance'),
    ('Cámara web', 'Logitech C270'),
    ('Cámara web', 'Logitech C920'),
    ('Cámara web', 'Logitech Brio 4K'),
    ('Cámara web', 'Microsoft LifeCam HD-3000'),
    ('Cámara web', 'Razer Kiyo Pro'),
    ('Teclado / ratón', 'Logitech MK270'),
    ('Teclado / ratón', 'Logitech MX Keys'),
    ('Teclado / ratón', 'Logitech MX Master 3S'),
    ('Teclado / ratón', 'Logitech M185'),
    ('Audífonos / diadema', 'Jabra Evolve2 40'),
    ('Audífonos / diadema', 'Jabra Evolve2 65'),
    ('Audífonos / diadema', 'Jabra BIZ 2300'),
    ('Audífonos / diadema', 'Poly Voyager Focus 2'),
    ('Audífonos / diadema', 'Sony WH-1000XM5'),
    ('Estación de acoplamiento', 'Dell WD19S'),
    ('Estación de acoplamiento', 'Dell WD22TB4'),
    ('Estación de acoplamiento', 'Lenovo ThinkPad Universal USB-C Dock'),
    ('Estación de acoplamiento', 'HP USB-C Dock G5'),
    ('Estación de acoplamiento', 'CalDigit TS4'),
    ('Teléfono IP', 'Cisco IP Phone 7841'),
    ('Teléfono IP', 'Cisco IP Phone 8841'),
    ('Teléfono IP', 'Yealink T31P'),
    ('Teléfono IP', 'Yealink T54W'),
    ('Teléfono IP', 'Grandstream GRP2612'),
    ('Teléfono IP', 'Poly CCX 400'),
    ('Central telefónica IP', 'Grandstream UCM6302'),
    ('Central telefónica IP', 'Cisco Business Edition 6000'),
    ('Central telefónica IP', 'Avaya IP Office 500 V2'),
    ('Central telefónica IP', 'Panasonic KX-NS700'),
    ('Videoconferencia', 'Poly Studio X50'),
    ('Videoconferencia', 'Poly Studio USB'),
    ('Videoconferencia', 'Logitech Rally Bar'),
    ('Videoconferencia', 'Logitech MeetUp'),
    ('Videoconferencia', 'Cisco Room Kit Mini'),
    ('Videoconferencia', 'Yealink MeetingBar A20'),
    ('Videoconferencia', 'Jabra PanaCast 50'),
    ('Radio portátil', 'Motorola DEP450'),
    ('Radio portátil', 'Kenwood TK-3402'),
    ('Radio portátil', 'Hytera BD505'),
    ('Smartphone', 'Apple iPhone 15'),
    ('Smartphone', 'Apple iPhone 16 Pro'),
    ('Smartphone', 'Samsung Galaxy S24'),
    ('Smartphone', 'Samsung Galaxy A55'),
    ('Smartphone', 'Google Pixel 9'),
    ('Smartphone', 'Xiaomi Redmi Note 13'),
    ('Smartphone', 'Motorola Moto G84'),
    ('Tableta', 'Apple iPad 10.ª generación'),
    ('Tableta', 'Apple iPad Pro 11 M4'),
    ('Tableta', 'Samsung Galaxy Tab S9'),
    ('Tableta', 'Samsung Galaxy Tab A9+'),
    ('Tableta', 'Lenovo Tab M10 Plus'),
    ('Reloj inteligente', 'Apple Watch Series 10'),
    ('Reloj inteligente', 'Samsung Galaxy Watch7'),
    ('Reloj inteligente', 'Garmin Forerunner 265'),
    ('Cámara IP', 'Hikvision DS-2CD2043G2-I'),
    ('Cámara IP', 'Hikvision DS-2CD2143G2-I'),
    ('Cámara IP', 'Dahua IPC-HFW2431S-S-S2'),
    ('Cámara IP', 'Axis M3106-L Mk II'),
    ('Cámara IP', 'Axis P3265-LVE'),
    ('Cámara IP', 'Ubiquiti UniFi G4 Bullet'),
    ('Cámara IP', 'Hanwha XNV-6080R'),
    ('NVR', 'Hikvision DS-7608NI-K2/8P'),
    ('NVR', 'Dahua NVR4108HS-8P-4KS2/L'),
    ('NVR', 'Ubiquiti UniFi UNVR'),
    ('Control de acceso', 'HID Signo 20'),
    ('Control de acceso', 'HID Signo 40'),
    ('Control de acceso', 'ZKTeco inBio 460'),
    ('Control de acceso', 'Suprema BioStation 2'),
    ('Domótica / IoT', 'Amazon Echo Dot 5.ª generación'),
    ('Domótica / IoT', 'Google Nest Mini'),
    ('Domótica / IoT', 'Google Nest Learning Thermostat'),
    ('Domótica / IoT', 'Philips Hue Bridge'),
    ('Domótica / IoT', 'TP-Link Tapo P100'),
    ('Domótica / IoT', 'Shelly Plus 1'),
    ('PLC', 'Siemens SIMATIC S7-1200'),
    ('PLC', 'Siemens SIMATIC S7-1500'),
    ('PLC', 'Allen-Bradley CompactLogix 5380'),
    ('PLC', 'Schneider Modicon M221'),
    ('HMI', 'Siemens SIMATIC KTP700 Basic'),
    ('HMI', 'Allen-Bradley PanelView 5310'),
    ('Dron', 'DJI Mini 4 Pro'),
    ('Dron', 'DJI Mavic 3 Enterprise'),
    ('Dron', 'DJI Matrice 350 RTK'),
    ('Visor VR / AR', 'Meta Quest 3'),
    ('Visor VR / AR', 'Apple Vision Pro'),
    ('Visor VR / AR', 'Microsoft HoloLens 2'),
    ('Visor VR / AR', 'HTC Vive Focus 3')
) as v(categoria, producto)
join categorias c on c.nombre = v.categoria
on conflict (categoria_id, nombre) do nothing;

-- -----------------------------------------------------------------------
-- ROLLBACK (no se ejecuta solo -- correr a mano si hay que revertir esto)
-- -----------------------------------------------------------------------
-- drop table if exists productos;
-- drop table if exists categorias;
